//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monopoly.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объявить банкротство.
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} купил {1}.
        /// </summary>
        public static string bought {
            get {
                return ResourceManager.GetString("bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить.
        /// </summary>
        public static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Улучшить.
        /// </summary>
        public static string buystreet {
            get {
                return ResourceManager.GetString("buystreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы получаете карту шанса, если попадете сюда.
        /// </summary>
        public static string chance {
            get {
                return ResourceManager.GetString("chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} выбросил{1}.
        /// </summary>
        public static string cheatdice {
            get {
                return ResourceManager.GetString("cheatdice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передвинуть.
        /// </summary>
        public static string cheatmove {
            get {
                return ResourceManager.GetString("cheatmove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить игрока.
        /// </summary>
        public static string cheatplayer {
            get {
                return ResourceManager.GetString("cheatplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы получите общественную карту, если попадете сюда.
        /// </summary>
        public static string community {
            get {
                return ResourceManager.GetString("community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}{1}Эта недвижимость в настоящее время принадлежит {2}{1}Купить ее стоит ${3}Если в собственности одна &quot;коммунальная услуга&quot;, арендная плата в 4 раза больше суммы, указанной на кубиках {1}Если в собственности обе &quot;коммунальные услуги&quot;, арендная плата в 10 раз больше суммы, указанной на кубиках. {1} Стоимость заложения составляет ${4}.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} заплатил ${1} игроку {2}.
        /// </summary>
        public static string companypay {
            get {
                return ResourceManager.GetString("companypay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить ход.
        /// </summary>
        public static string dice {
            get {
                return ResourceManager.GetString("dice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} понизил{1}.
        /// </summary>
        public static string downgrade {
            get {
                return ResourceManager.GetString("downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закончить ход.
        /// </summary>
        public static string endturn {
            get {
                return ResourceManager.GetString("endturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вы попадете сюда, то получите бесплатную парковку..
        /// </summary>
        public static string freeparking {
            get {
                return ResourceManager.GetString("freeparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} нашел спрятанную сумку с ${1} в ней.
        /// </summary>
        public static string freeparkingpay {
            get {
                return ResourceManager.GetString("freeparkingpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра закончена.
        /// </summary>
        public static string gameover {
            get {
                return ResourceManager.GetString("gameover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на получил.
        /// </summary>
        public static string got {
            get {
                return ResourceManager.GetString("got", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы попали в тюрьму за кражу мыла.
        /// </summary>
        public static string gotojail {
            get {
                return ResourceManager.GetString("gotojail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в лучшее место.
        /// </summary>
        public static string jail {
            get {
                return ResourceManager.GetString("jail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} сидит в тюрьме.
        /// </summary>
        public static string jailperson {
            get {
                return ResourceManager.GetString("jailperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы посещаете тюрьму, чтобы отдать своему приятелю курсовой проект, потому что он как-то потерял его..
        /// </summary>
        public static string jailvisit {
            get {
                return ResourceManager.GetString("jailvisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить игру.
        /// </summary>
        public static string loadgame {
            get {
                return ResourceManager.GetString("loadgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер улиц.
        /// </summary>
        public static string managestreets {
            get {
                return ResourceManager.GetString("managestreets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заложить.
        /// </summary>
        public static string mortage {
            get {
                return ResourceManager.GetString("mortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} заложил{1}.
        /// </summary>
        public static string mortaged {
            get {
                return ResourceManager.GetString("mortaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} перешел на {1}.
        /// </summary>
        public static string moves {
            get {
                return ResourceManager.GetString("moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать новую игру.
        /// </summary>
        public static string newgame {
            get {
                return ResourceManager.GetString("newgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заложен.
        /// </summary>
        public static string onmortage {
            get {
                return ResourceManager.GetString("onmortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деньги за бесплатную парковку:.
        /// </summary>
        public static string parkingmoney {
            get {
                return ResourceManager.GetString("parkingmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {12} эта недвижимость в настоящее время принадлежит {1} {12} {2} покупка этой {12} недвижимости стоит ${3} Аренда ${4} {12} Затраты на модернизацию улицы: ${5} {12} С 1 домом ваша арендная плата составляет: ${6} {12} С 2 домами ваша арендная плата составляет: ${7} {12} С 3 домом арендная плата составляет: ${8} {12} С 4 домом арендная плата составляет: ${9} {12} С гостиницей арендная плата составляет: ${10} {12} Стоимость заложения: ${11} {12} Если у вас есть весь город, то арендная плата удваивается.&quot;.
        /// </summary>
        public static string property {
            get {
                return ResourceManager.GetString("property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На улице {1} было построено домов {1}.
        /// </summary>
        public static string propertyhouses {
            get {
                return ResourceManager.GetString("propertyhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на никто.
        /// </summary>
        public static string propertyowner {
            get {
                return ResourceManager.GetString("propertyowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}{1} эта железная дорога в настоящее время принадлежит {2} {1} покупка этой {1} стоит ${3}. Аренда при наличии 1 железной дороги: ${4}{1} Аренда при наличии 2 железных дорог: ${5}{1} Аренда при наличии 3 железных дорог: ${6}{1} Аренда при наличии 4 железных дорог: ${7}{1} Стоимость заложения: ${8}.
        /// </summary>
        public static string railroad {
            get {
                return ResourceManager.GetString("railroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} заплатил ${1} игроку {2}.
        /// </summary>
        public static string railroadpay {
            get {
                return ResourceManager.GetString("railroadpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Понизить.
        /// </summary>
        public static string sellstreet {
            get {
                return ResourceManager.GetString("sellstreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}{1}Если вы попадете на это поле, вы получите $400 {1}Если вы пройдете эту плитку, вы получите $200.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} попал на поле старта и получил дополнительно $400.
        /// </summary>
        public static string startmoney {
            get {
                return ResourceManager.GetString("startmoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, вам придется платить налоги, но не волнуйтесь {0} В реальной жизни вам не придется платить 10% от вашей общей чистой стоимости!.
        /// </summary>
        public static string taxes {
            get {
                return ResourceManager.GetString("taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} пришлось заплатить ${1}.
        /// </summary>
        public static string taxespay10 {
            get {
                return ResourceManager.GetString("taxespay10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} пришлось заплатить $200.
        /// </summary>
        public static string taxespay200 {
            get {
                return ResourceManager.GetString("taxespay200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} выбил {1} и {2}.
        /// </summary>
        public static string throwdice {
            get {
                return ResourceManager.GetString("throwdice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите &apos;b&apos;, чтобы быстро купить недвижимость.
        /// </summary>
        public static string tooltipbuy {
            get {
                return ResourceManager.GetString("tooltipbuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите &apos;t&apos;, чтобы быстро бросить игральную кость..
        /// </summary>
        public static string tooltipdice {
            get {
                return ResourceManager.GetString("tooltipdice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите &apos;m&apos;, чтобы быстро управлять своими объектами.
        /// </summary>
        public static string tooltipmanage {
            get {
                return ResourceManager.GetString("tooltipmanage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите &apos;e&apos;, чтобы быстро завершить свой ход..
        /// </summary>
        public static string tooltipturn {
            get {
                return ResourceManager.GetString("tooltipturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество игроков:.
        /// </summary>
        public static string totalplayers {
            get {
                return ResourceManager.GetString("totalplayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} улучшил {1}.
        /// </summary>
        public static string upgrade {
            get {
                return ResourceManager.GetString("upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость улучшения.
        /// </summary>
        public static string upgradecost {
            get {
                return ResourceManager.GetString("upgradecost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выиграл!.
        /// </summary>
        public static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
    }
}
